version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8003:8003
      - 50051:50051
    volumes:
      - .:/go/app
    env_file:
      - .envrc
      - deployment.env
