// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: voucher.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoucherServiceClient is the client API for VoucherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoucherServiceClient interface {
	ValidateVoucherCode(ctx context.Context, in *VoucherCodeRequest, opts ...grpc.CallOption) (*VoucherStatusResponse, error)
	GetVoucherByCode(ctx context.Context, in *VoucherCodeRequest, opts ...grpc.CallOption) (*VoucherResponse, error)
}

type voucherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherServiceClient(cc grpc.ClientConnInterface) VoucherServiceClient {
	return &voucherServiceClient{cc}
}

func (c *voucherServiceClient) ValidateVoucherCode(ctx context.Context, in *VoucherCodeRequest, opts ...grpc.CallOption) (*VoucherStatusResponse, error) {
	out := new(VoucherStatusResponse)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/ValidateVoucherCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) GetVoucherByCode(ctx context.Context, in *VoucherCodeRequest, opts ...grpc.CallOption) (*VoucherResponse, error) {
	out := new(VoucherResponse)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/GetVoucherByCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherServiceServer is the server API for VoucherService service.
// All implementations must embed UnimplementedVoucherServiceServer
// for forward compatibility
type VoucherServiceServer interface {
	ValidateVoucherCode(context.Context, *VoucherCodeRequest) (*VoucherStatusResponse, error)
	GetVoucherByCode(context.Context, *VoucherCodeRequest) (*VoucherResponse, error)
	mustEmbedUnimplementedVoucherServiceServer()
}

// UnimplementedVoucherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoucherServiceServer struct {
}

func (UnimplementedVoucherServiceServer) ValidateVoucherCode(context.Context, *VoucherCodeRequest) (*VoucherStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateVoucherCode not implemented")
}
func (UnimplementedVoucherServiceServer) GetVoucherByCode(context.Context, *VoucherCodeRequest) (*VoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoucherByCode not implemented")
}
func (UnimplementedVoucherServiceServer) mustEmbedUnimplementedVoucherServiceServer() {}

// UnsafeVoucherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoucherServiceServer will
// result in compilation errors.
type UnsafeVoucherServiceServer interface {
	mustEmbedUnimplementedVoucherServiceServer()
}

func RegisterVoucherServiceServer(s grpc.ServiceRegistrar, srv VoucherServiceServer) {
	s.RegisterService(&VoucherService_ServiceDesc, srv)
}

func _VoucherService_ValidateVoucherCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoucherCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).ValidateVoucherCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/ValidateVoucherCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).ValidateVoucherCode(ctx, req.(*VoucherCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_GetVoucherByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoucherCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).GetVoucherByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/GetVoucherByCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).GetVoucherByCode(ctx, req.(*VoucherCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoucherService_ServiceDesc is the grpc.ServiceDesc for VoucherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoucherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voucher.VoucherService",
	HandlerType: (*VoucherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateVoucherCode",
			Handler:    _VoucherService_ValidateVoucherCode_Handler,
		},
		{
			MethodName: "GetVoucherByCode",
			Handler:    _VoucherService_GetVoucherByCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voucher.proto",
}
